### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by dfarinam**
Added Spanish translation

### CODE REVIEW

**Review by KjellMorgenstern — COMMENTED** [review]
The files look identical?

**Comment by dfarinam** [comment]
> 
> 
> The files look identical?

Sure I'm new in Git, so I'm not sure what to do to complete a file update in Git. There are more updates to come. Translation is 60% complete.

**Comment by KjellMorgenstern** [comment]
We are testing a new frontend for translations, would you like to have a look?

**Comment by dfarinam** [comment]
> 
> 
> We are testing a new frontend for translations, would you like to have a look?

Sure. 

By the way, do I have to do anything else with this push request? I'm not familiar at all with Git.

**Comment by KjellMorgenstern** [comment]
Please contact me via email or the support form, so I can email you an invitation.

**Comment by KjellMorgenstern** [comment]
PS. Indeed the PR only contains whitespaces changes, nothing else. I will close it, you can open a new one if you already have changes, or maybe there is even an easy way to transfer them to the translations frontend

**Pull request closed without merging**
