### PR TITLE
minimise initial size of cloned parts repository in releases

### PR DESCRIPTION
**Pull request by cjmayo**
Don't include the history or alternate branches.

### CODE REVIEW

**Comment by aknoerig** [comment]
Good point! I guess we didn't think of it because libgit2 doesn't support the --depth parameter. 
Did you test this with an update inside of Fritzing to make sure libgit2 doesn't get confused?

**Comment by cjmayo** [comment]
No I haven't tried libgit2 from the GUI yet - I have problems with filepaths at runtime after install from source. I do have some ideas on that which are nearly ready to share!

**Comment by cjmayo** [comment]
Good catch. It doesn't update from the GUI. libgit2 doesn't support shallow clones:
https://github.com/libgit2/libgit2/issues/3058

```--single-branch --branch master```  creates a repository that at the moment is only slightly bigger than the shallow one, but much smaller than a complete one (178M versus 293M).

I'll wait and see if this works from the GUI.

**Comment by cjmayo** [comment]
Confirmed that works from the GUI. Commit updated.

**Comment by aknoerig** [comment]
Great, thanks!!

**Pull request merged**
