### PR TITLE
Update European Portuguese translation

### PR DESCRIPTION
**Pull request by BrunoRamalhete**
Hi,

Added new strings in the European Portuguese translation (pt_PT).
I also fixed some typos and fixed some words.

I attached the .ts file, archived in zip, so GitHub can accept it.

Thanks a lot!
Bruno Santos Ramalhete
[fritzing_pt_pt.zip](https://github.com/fritzing/fritzing-app/files/6417906/fritzing_pt_pt.zip)

### CODE REVIEW

**Comment by KjellMorgenstern** [comment]
Hello Bruno I have a question about the translation of peça / parte .
I think this is similar to English piece and part and also German Stück and Teil. Is there a specific reason you changed the translation to 'peça' ?

**Comment by KjellMorgenstern** [comment]
```
         <source>Fritzing Files (*%1 *%2 *%3);;Fritzing Part (*%1);;Fritzing Bin (*%2);;Fritzing Shareable Bin (*%3)</source>
-        <translation>Ficheiros Fritzing (*%1 *%2 *%3);;Parte Fritzing (*%1);;Binário Fritzing (*%2);;Binário Partilhávl Fritzing (*%3)</translation>
+        <translation>Fritzing Files (*%1 *%2 *%3);;Fritzing Part (*%1);;Fritzing Bin (*%2);;Fritzing Shareable Bin (*%3)</translation>
     </message>

```
For this string, the existing translation was replaced with English. I guess this was not intended?

**Comment by KjellMorgenstern** [comment]
You changed the from 2nd singular to the politnes pronoun. This is important for brazilian portugues, but I am not so sure about portugues from portugal. My impression is that would be similar to German, where Fritzing uses the 2nd singular?

**Comment by BrunoRamalhete** [comment]
Hi Kjell,

I think I was a bit confused about this one. Parts are about components and
something like that?

If it’s I thought it could be the word “peça”.

So I have to replace like it is in Brazilian Portuguese.



Kjell ***@***.***> escreveu em sex., 21/05/2021 às 11:23 :

**Comment by BrunoRamalhete** [comment]
Hi,

I made some fixes in the European Portuguese translation, I fixed the word "peça" and replaced it by "componente" as it is in the Brazilian Portuguese. I understand now what the Fritzing parts mean, so it is about components. The translations are now similar as in the Brazilian Portuguese.

I will attach the file here, and I will upload/update in Weblate.
[fritzing_pt_pt.zip](https://github.com/fritzing/fritzing-app/files/6601325/fritzing_pt_pt.zip)

**Comment by KjellMorgenstern** [comment]
I think these changes have been merged via weblate.

**Pull request closed without merging**
