### PR TITLE
Spanish translation reloaded

### PR DESCRIPTION
**Pull request by dfarinam**
Spanish translation is deeply changed. Completion rate is increased. Most of it has been double-checked with my own compilation.

### CODE REVIEW

**Comment by dfarinam** [comment]
I expect this time the files are the right ones.

**Comment by KjellMorgenstern** [comment]
Hi, I looked at the PR, but it still seems empty. Could you provide one example of a phrase that you changed, so I can look into that phrase in detail and find out what might have gone wrong?

You may also contact me directly via the fritzing contact page.

**Comment by dfarinam** [comment]
I guess I pushed the "old" translation file. I've pushed the new one dated 2021-05-29. I have also attached it in this post.
[fritzing_es.zip](https://github.com/fritzing/fritzing-app/files/6719966/fritzing_es.zip)

**Comment by KjellMorgenstern** [comment]
Could you please provide one example of a translated string? It would help me to check that I processed your file correctly.

**Comment by dfarinam** [comment]
Sure, I'll do It.

Thanks

**Comment by dfarinam** [comment]
Hello, An example: Rotate the label by 135 degrees counter clockwise Girar la etiqueta 135 grados en sentido antihorario  Snapshot from Qt Thanks,David  De: David FariñaEnviado: domingo, 27 de junio de 2021 11:22Para: fritzing/fritzing-appAsunto: Re: [fritzing/fritzing-app] Spanish translation reloaded (#3834) Sure, I'll do It. Thanks El dom., 27 jun. 2021 11:01, Kjell ***@***.***> escribió:Could you please provide one example of a translated string? It would help me to check that I processed your file correctly.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by dfarinam** [comment]
Another example: Create Trace from Ratsnest Crea pistas partiendo de conexiones Snapshot from Qt  De: David FariñaEnviado: domingo, 27 de junio de 2021 12:50Para: fritzing/fritzing-appAsunto: RE: [fritzing/fritzing-app] Spanish translation reloaded (#3834) Hello, An example: Rotate the label by 135 degrees counter clockwise Girar la etiqueta 135 grados en sentido antihorario  Snapshot from Qt Thanks,David  De: David FariñaEnviado: domingo, 27 de junio de 2021 11:22Para: fritzing/fritzing-appAsunto: Re: [fritzing/fritzing-app] Spanish translation reloaded (#3834) Sure, I'll do It. Thanks El dom., 27 jun. 2021 11:01, Kjell ***@***.***> escribió:Could you please provide one example of a translated string? It would help me to check that I processed your file correctly.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by dfarinam** [comment]
I also see in the curent fritzing_es.ts file uploaded whithin this pull request (starting from line 380):
"...
    <message>
        <location filename="../src/partsbinpalette/binmanager/binmanager.cpp" line="396"/>
        <source>Select a Fritzing Parts Bin file to open</source>
        <translation>Selecione un archivo de almacén de componentes Fritzing</translation>
..."

This is also part of my translation

imagen

**Pull request closed without merging**
