### PR TITLE
added more capacitor values, fixes 3713.

### PR DESCRIPTION
**Pull request by failiz**
Hi,
I am not sure if I should add some of these values to the properties capacitance5mm, capacitance7.5mm, etc. When are they used? 
Cheers,
Andres

### CODE REVIEW

**Comment by KjellMorgenstern** [comment]
You can see the usage of the capacitance5mm ... tables when looking for "foil capacitor" in the parts search.

**Comment by KjellMorgenstern** [comment]
Do you think the values added are very common?
The original issue #3713 only asked for a 2.2mF capacitor.
 It is possible to enter a custom number to the capacitance field in case the value is not in the table. So, the table just is for convenience, and maybe to help beginners finding their capacitor. If the list includes rare settings, it might be less helpful.

**Comment by failiz** [comment]
I do not have strong feelings about this. 
My intention was to provide all the [E3 series values](https://en.wikipedia.org/wiki/E_series_of_preferred_numbers#E6). I checked in RS (Amidata) and there are plenty of these values. However, I do not know if there are very used. 
This issue is related to #1455. The resistor implement the E6 series. 
Let me know if you prefer to only add that specific one.

**Comment by KjellMorgenstern** [comment]
E3 sounds good. And there are the issues with manually entering a value (it works but somehow you need multiple attempts).

**Pull request merged**
