### PR TITLE
Added shorcuts for rotting, flipping and find part. Fixes #3582

### LINKED ISSUE #3582: Support CTRL-F for searching a component
## Problem
Many times I am searching for a component I use CTRL-F but the shortcut is not supported in windows.

## Proposed Solution
Add shortcut for searching a component

### PR DESCRIPTION
**Pull request by failiz**
When I made the examples for the simulator, making the circuits took too much time. These shortcuts will help to make Fritzing more user friendly. I used R and F (without control) as it is the same as in Kicad.

### CODE REVIEW

**Comment by KjellMorgenstern** [comment]
I'd like to review the keys. Using the same keys as as KiCad could be a point, but my intuiton is  "[" and "]" for rotating and "|" "_" for flipping. One reason for it: I think man graphic tools use [ and ] (what does Inkscape use?)

**Comment by failiz** [comment]
No Ida about Inkscape or man graphic tools, but it could be nice to check. By the way, I found after submitting this PR that there is already a shortcut for rotating in Fritzing (rotating the selection). It is CTRL+R and other variations also exist. As this action is not in the menues, it is not displayed in the menues and it is difficult to find (I found it by searching in the code). Maybe it should be added to the menu, but anly rotate 90 degrees. I do not think that people use the 45 degrees option so often.

**Comment by KjellMorgenstern** [comment]
We added the search key, and 90 degree rotation with "[" and "]" . The label alignment in breadboard view was not changed, I think in most cases it is preferable to have the lables aligned, and rotating a single label is a special case.

**Comment by failiz** [comment]
I am ok with not changing the lables in the BBview, but I think the labels should be readable in the SCH view at all times. I added some comments in #684.

**Pull request closed without merging**
